//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCMS.MVC4.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VCMS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VCMS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCMS.MVC4.Web.App_GlobalResources.VCMS", typeof(VCMS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu .
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người truy cập.
        /// </summary>
        public static string ac {
            get {
                return ResourceManager.GetString("ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng của bạn .
        /// </summary>
        public static string addtocart {
            get {
                return ResourceManager.GetString("addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARISTA VIỆT NAM QUẢNG CÁO.
        /// </summary>
        public static string advert {
            get {
                return ResourceManager.GetString("advert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Tất cả sản phẩm.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        public static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file hướng dẫn sử dụng .
        /// </summary>
        public static string attachment_download {
            get {
                return ResourceManager.GetString("attachment_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BARISTA VIỆT NAM.
        /// </summary>
        public static string barista {
            get {
                return ResourceManager.GetString("barista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem lại hóa đơn.
        /// </summary>
        public static string bill {
            get {
                return ResourceManager.GetString("bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng để lại thông tin.
        /// </summary>
        public static string body {
            get {
                return ResourceManager.GetString("body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh miền nam.
        /// </summary>
        public static string branch {
            get {
                return ResourceManager.GetString("branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string cart {
            get {
                return ResourceManager.GetString("cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ.
        /// </summary>
        public static string cart1 {
            get {
                return ResourceManager.GetString("cart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string catalog {
            get {
                return ResourceManager.GetString("catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string catalogue {
            get {
                return ResourceManager.GetString("catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/TP.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp vào để xem.
        /// </summary>
        public static string clickview {
            get {
                return ResourceManager.GetString("clickview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cà phê nhân.
        /// </summary>
        public static string coffeebeans {
            get {
                return ResourceManager.GetString("coffeebeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cà phê xuất khẩu.
        /// </summary>
        public static string coffeeexpo {
            get {
                return ResourceManager.GetString("coffeeexpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cà phê gia đình.
        /// </summary>
        public static string coffeefa {
            get {
                return ResourceManager.GetString("coffeefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cà phê làm quà biếu.
        /// </summary>
        public static string coffeegif {
            get {
                return ResourceManager.GetString("coffeegif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cà phê bán sỉ nội địa.
        /// </summary>
        public static string coffeewho {
            get {
                return ResourceManager.GetString("coffeewho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng thành công. Thông tin đặt hàng của quý sẽ được chúng tôi cập nhật sớm nhất và gửi cho quý khách trong thời gian sớm nhất . Cám ơn quý khách đã mua hàng tại website của chúng tôi..
        /// </summary>
        public static string com {
            get {
                return ResourceManager.GetString("com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra, vui lòng thử lại sau..
        /// </summary>
        public static string contact_response_failed {
            get {
                return ResourceManager.GetString("contact_response_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã liên hệ với chúng tôi. Mọi thông tin, câu hỏi sẽ được hồi đáp trong thời gian sớm nhất có thể..
        /// </summary>
        public static string contact_response_ok {
            get {
                return ResourceManager.GetString("contact_response_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string conus {
            get {
                return ResourceManager.GetString("conus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tư vấn khách hàng.
        /// </summary>
        public static string customer_consulting {
            get {
                return ResourceManager.GetString("customer_consulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNĐ.
        /// </summary>
        public static string dola {
            get {
                return ResourceManager.GetString("dola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm.
        /// </summary>
        public static string ds {
            get {
                return ResourceManager.GetString("ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string f {
            get {
                return ResourceManager.GetString("f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        public static string F_Projects {
            get {
                return ResourceManager.GetString("F_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string ff {
            get {
                return ResourceManager.GetString("ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực tìm.
        /// </summary>
        public static string found {
            get {
                return ResourceManager.GetString("found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng miễn phí.
        /// </summary>
        public static string free_delivery {
            get {
                return ResourceManager.GetString("free_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string g {
            get {
                return ResourceManager.GetString("g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        public static string hight_product {
            get {
                return ResourceManager.GetString("hight_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền vào mẫu dưới đây khi bạn có bất kỳ yêu cầu hay góp ý nào..
        /// </summary>
        public static string inf {
            get {
                return ResourceManager.GetString("inf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cà phê.
        /// </summary>
        public static string infocoffee {
            get {
                return ResourceManager.GetString("infocoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa.
        /// </summary>
        public static string keyword {
            get {
                return ResourceManager.GetString("keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực mất.
        /// </summary>
        public static string lost {
            get {
                return ResourceManager.GetString("lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to họ.
        /// </summary>
        public static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ &amp; tên.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục chính.
        /// </summary>
        public static string navi {
            get {
                return ResourceManager.GetString("navi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        public static string new_product {
            get {
                return ResourceManager.GetString("new_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức mới.
        /// </summary>
        public static string news1 {
            get {
                return ResourceManager.GetString("news1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường hợp khách hàng yêu cầu giao hàng ra nước ngoài và ngoài tỉnh, vui lòng liên lạc trực tiếp với Á Châu qua &lt;br /&gt;Email: e-store@capheachau.com.vn, để được thông tin về phí vận chuyển &amp; thời điểm nhận hàng.&lt;br /&gt;
        ///Thông tin chuyển khoản: &lt;br /&gt;
        ///Chủ TK:  Đàm Công Tiến&lt;br /&gt;
        ///Số TK:  0600 514 04 796&lt;br /&gt;
        ///Tại ngân hàng Sacombank - CN Bình Tân-Tp.HCM
        /// &lt;br /&gt; &lt;br /&gt;
        ///Chủ TK:  Đàm Công Tiến&lt;br /&gt;
        ///Số TK:  140 860 159&lt;br /&gt;
        ///Tại ngân hàng ACB - PGD Tân Sơn Nhì.
        /// </summary>
        public static string notecheck {
            get {
                return ResourceManager.GetString("notecheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string num {
            get {
                return ResourceManager.GetString("num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang trực tuyến .
        /// </summary>
        public static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string order_form {
            get {
                return ResourceManager.GetString("order_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} khác.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string pri {
            get {
                return ResourceManager.GetString("pri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá.
        /// </summary>
        public static string pricelist {
            get {
                return ResourceManager.GetString("pricelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tiếp.
        /// </summary>
        public static string readmore {
            get {
                return ResourceManager.GetString("readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được để trống.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gởi.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sơ đồ website.
        /// </summary>
        public static string sitemap {
            get {
                return ResourceManager.GetString("sitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        public static string sum {
            get {
                return ResourceManager.GetString("sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ trực tuyến.
        /// </summary>
        public static string sup_online {
            get {
                return ResourceManager.GetString("sup_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trà oolong.
        /// </summary>
        public static string taiwan {
            get {
                return ResourceManager.GetString("taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm &gt;.
        /// </summary>
        public static string View_Project {
            get {
                return ResourceManager.GetString("View_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Xem tất cả.
        /// </summary>
        public static string viewall {
            get {
                return ResourceManager.GetString("viewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string viewDetail {
            get {
                return ResourceManager.GetString("viewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê truy cập.
        /// </summary>
        public static string visitor {
            get {
                return ResourceManager.GetString("visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string zcode {
            get {
                return ResourceManager.GetString("zcode", resourceCulture);
            }
        }
    }
}
